---
title: The CLAIMED framework
---
stateDiagram-v2
    Python --> C3
    R --> C3
    Notebooks --> C3
    ... --> C3
    C3 --> Kubeflow&nbsp;Component
    C3 --> Kubernetes&nbsp;Job
    C3 --> CLI
    C3 --> LSF
    C3 --> CWL
    C3 --> Slurm
    C3 --> IBM&nbsp;CPD&nbsp;(Watson&nbsp;Studio)
    C3 --> RedHat&nbsp;OpenShift&nbsp;Pipelines
    C3 --> ....

