apiVersion: batch/v1
kind: Job
metadata:
  name: image-tiling-with-metadata-adjustment
spec:
  template:
    spec:
      containers:
      - name: image-tiling-with-metadata-adjustment
        image: docker.io/lorenzweingart/claimed-image-tiling-with-metadata-adjustment:0.1
        workingDir: /opt/app-root/src/
        command: ["/opt/app-root/bin/ipython","claimed_image-tiling-with-metadata_adjustment.ipynb"]
        env:
        - name: log_level
          value: value_of_log_level
        - name: directory_path
          value: value_of_directory_path
        - name: destination
          value: value_of_destination
        - name: tile_size_x
          value: value_of_tile_size_x
        - name: tile_size_y
          value: value_of_tile_size_y
        - name: stride_x
          value: value_of_stride_x
        - name: stride_y
          value: value_of_stride_y
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: image_pull_secret